version: "3.8"

services:
  app:
    build: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    container_name: db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 10s
      test: ["CMD", "pg_isready", "-U", "root", "-d", "users"]
      timeout: 10s
    image: postgres:latest
    networks:
      - node-network
    ports:
      - "5432:5432"

networks:
  node-network:
    driver: bridge
